apiVersion: v1
kind: Namespace
metadata:
  name: drawio
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-http01
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/service-weight: ''
  generation: 3
  name: drawio-ingress
  namespace: drawio
spec:
  tls:
    - hosts:
        - drawio.seaurl.com
      secretName: drawio-ingress
  rules:
    - host: drawio.seaurl.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: drawio
                port:
                  number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: drawio
  namespace: drawio
  labels:
    app: draw.io
spec:
  # 使用ip访问，所以设置成NodePort
  type: NodePort
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  ports:
    - name: http
      port: 8080
  selector:
    app: draw.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drawio
  namespace: drawio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: draw.io
  template:
    metadata:
      labels:
        app: draw.io
    spec:
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/com-seaurl/seaurl-drawio:<tag>
          imagePullPolicy: IfNotPresent
          name: drawio
          ports:
            - containerPort: 8080
---